### PR TITLE
Added self-host section and other stuff

### PR DESCRIPTION
**Pull request by voiding**
Please. This is not a bad change. I will not be upset if you don't merge but it's good in terms of licensing. So, please.

I added:
```
## Self-host
This bot is hosted on heroku, meaning: 

**-** It is not self-hosted
**-** We will not help with self-hosting. The support server is for Catbot support only.
**-** You cannot use the same name or icon. This is in violation of our copyright laws.
**-** We won't stop you trying to self-host, feel free to, but we won't help you if you need help or mess up.

With this being said, you're free to self-host this if you know what you're doing but we won't provide support for this specific area.
```

### CODE REVIEW

**Comment by n1ghtc4t** [comment]
oh

**Comment by n1ghtc4t** [comment]
idk looks decent

**Comment by n1ghtc4t** [comment]
ok i'll merge

**Comment by n1ghtc4t** [comment]
have a nice day

**Comment by whomhasfallen** [comment]
Edited the commit message lol.

**Pull request merged**
