### PR TITLE
Correction

### PR DESCRIPTION
**Pull request by voiding**
When referring to guilds, you use on instead of in.

### CODE REVIEW

**Comment by ghost** [comment]
Do you know how to mind your own business

**Comment by n1ghtc4t** [comment]
I can fix this myself. I don't need input from you, void.

**Review by n1ghtc4t — COMMENTED** [review]
I can do these myself

**Comment by whomhasfallen** [comment]
It may be frustrating to have to deal with the incorrect way of wording, but I advise you not to tamper with the spelling/grammatical errors in the code. You're allowed to correct these errors in the README, if any.

**Comment by whomhasfallen** [comment]
Only ever change the code if you know what you're doing. Thank you.

**Pull request closed without merging**
